services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdac
    ports:
      - "5432:5432"
    volumes:
      - sdac_pg:/var/lib/postgresql/data

volumes:
  sdac_pg:

