services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdak
    ports:
      - "5432:5432"
    volumes:
      - sdak_pg:/var/lib/postgresql/data

volumes:
  sdak_pg:
